### ISSUE TITLE
qemu 内网卡没有起来

### ISSUE THREAD

**Issue by veritas501** [ssst0n3/ctf_dirty-pipe-escape-rw#1]
启动参数：
```
qemu-system-x86_64 \
  -hda ctf_dirty-pipe-escape-rw_debug_202204181408.shrunk.qcow2 \
  -smp 12 \
  -m 2048M \
  -nographic -enable-kvm \
  -netdev user,id=t0,hostfwd=tcp::20022-:22 -device e1000,netdev=t0,id=nic0
```

![image](https://user-images.githubusercontent.com/25763545/163804736-0f75e7f6-da0c-4ed4-a025-a5a6ebb507d4.png)

**Comment by ssst0n3** [comment]
我的锅，从云上导下来镜像后，没有检查。cloud-init把mac地址给绑定了。

可以先执行以下脚本解决，下一步我会更新本地调试环境的镜像，解决这个问题。公网靶机不受此问题影响

```
cat <<EOF>/etc/netplan/50-cloud-init.yaml
network:
    version: 2
    ethernets:
        ens3:
            dhcp4: true
EOF
netplan apply
touch /etc/cloud/cloud-init.disabled
cloud-init clean
reboot
```

**Comment by ssst0n3** [comment]
已解决, 请使用上述脚本或以下版本镜像

https://ctf-challenges.obs.cn-south-1.myhuaweicloud.com/2022/hwctf_month-Qualifier-202204/container/dirty-pipe-escape-rw/ctf_dirty-pipe-escape-rw-debug_202204182133.shrunk.qcow2

**Comment by veritas501** [comment]
太敬业了吧👍

**Comment by ssst0n3** [comment]
貌似大家都解决了？我先关闭这个issue了，有需要可以留言再打开
